import sys
sys.stdout.write('GET /index.html HTTP/1.0\r\n')
sys.stdout.write('Method = GET\n')
sys.stdout.write('Request-URL = /index.html\n')
sys.stdout.write('HTTP-Version = HTTP/1.0\n')
sys.stdout.write('<!DOCTYPE html>\n')
sys.stdout.write('<html>\n')
sys.stdout.write('<body>\n')
sys.stdout.write('<h1>COMP431</h1>\n')
sys.stdout.write('</body>\n')
sys.stdout.write('</html>\n')
sys.stdout.write('GET /index2.html HTTP/1.0\r\n')
sys.stdout.write('Method = GET\n')
sys.stdout.write('Request-URL = /index2.html\n')
sys.stdout.write('HTTP-Version = HTTP/1.0\n')
sys.stdout.write('404 Not Found: /index2.html\n')
sys.stdout.write('GET /cat.png HTTP/1.0\r\n')
sys.stdout.write('Method = GET\n')
sys.stdout.write('Request-URL = /cat.png\n')
sys.stdout.write('HTTP-Version = HTTP/1.0\n')
sys.stdout.write('501 Not Implemented: /cat.png\n')
